### PR TITLE
Update: Radio Group Operability (fixes: #83)

### LINKED ISSUE #83: Radio buttons in Accessibility Settings
### Subject of the issue/enhancement/features
Keyboard operation of "Readability" radio options is not consistent. The following behavior was observed:

- Up arrow consistently cycled focus backwards through all options
- Down arrow moved focus forward, but is trapped once focus lands on the "Small" option
- Left/right arrow keys do nothing 

To avoid confusion and better align with the default radio button experience we recommend allowing users to move back and forth through a radio grouping using up/right to move forward, and down/left to move backward. Forward/backwards navigation must allow users to consistently cycle through all option within a grouping.

[​https://www.w3.org/WAI/ARIA/apg/patterns/radio/](https://www.w3.org/WAI/ARIA/apg/patterns/radio/)

### PR DESCRIPTION
**Pull request by joe-replin**
[//]: # (Please title your PR according to eslint commit conventions)
[//]: # (See https://github.com/conventional-changelog/conventional-changelog/tree/master/packages/conventional-changelog-eslint#eslint-convention for details)

[//]: # (Link the PR to the original issue)

[//]: # (Delete Fix, Update, New and/or Breaking sections as appropriate)

### Update
* Fixes #83 
* Aligns better with [Radio Group Pattern](https://www.w3.org/WAI/ARIA/apg/patterns/radio/)
* Moves all template functions into view
* Inspired by radio group functions from [MCQ Component](https://github.com/adaptlearning/adapt-contrib-mcq)
* Moves event trigger into view (see #72)

[//]: # (List appropriate steps for testing if needed)
### Testing
1. Install locally and test with a screen reader.

[//]: # (Mention any other dependencies)

### Requires
* https://github.com/adaptlearning/adapt-contrib-core/pull/379

### CODE REVIEW

**Comment by joe-replin** [comment]
@oliverfoster, breaking off from this conversation: https://github.com/adaptlearning/adapt-contrib-core/issues/174#issuecomment-1533833898

Simply setting up these radio groups according to spec provides a minimal amount of working keyboard navigation, but the results are very inconsistent for me. I checked this pattern against the current MCQ and I'm receiving the same results there. More often than not, arrow keys aren't providing any response. 

The pattern here suggests that space, enter & arrow controls be implemented in order to use your keyboard to toggle the radio buttons.

https://www.w3.org/WAI/ARIA/apg/patterns/radio/

**Comment by oliverfoster** [comment]
This has never come up in accessiblity testing on the mcq or gmcq.

The examples you're showing are for when one isn't using `<input type="radio" />` and `<input type="checkbox" />`, the semantic elements which come with the correct default aria roles and most of keyboard behaviours, all except the space/enter behvaiour I think.

File: templates/Visua11ySettings.jsx [hunk 1]
```diff
@@ -148,21 +148,21 @@ export default function Visua11ySettings(props) {
             <div className="visua11ysettings__item-option-container" role='radiogroup' aria-labelledby='fontsize'>
 
               <div className='visua11ysettings__item-option'>
-                <input type='radio' value={config._fontSize._small} checked={visua11y.fontSize === config._fontSize._small} id='fontSize-small' name='fontSize' aria-label='Font Size - Small' onKeyPress={onKeyPress} onChange={onChange} onFocus={onItemFocus} onBlur={onItemBlur} />
+                <input type='radio' value={config._fontSize._small} checked={visua11y.fontSize === config._fontSize._small} id='fontSize-small' name='fontSize' aria-label={config._fontSize.smallLabel} onKeyPress={onKeyPress} onChange={onChange} onFocus={onItemFocus} onBlur={onItemBlur} />
```
Comment (joe-replin) [inline templates/Visua11ySettings.jsx:151]: This will make labels a numerical value and for medium font size, plainly say 'medium'. Is that a sufficient label?

Comment (oliverfoster) [reply templates/Visua11ySettings.jsx:151]: https://github.com/cgkineo/adapt-visua11y/blob/c8819e33491e86e95e094e4a723ea4185901e359/example.json#L65-L75

> this will make labels a numerical value

`smallLabel` should read `"Small"`

The labels should not be hardcoded in the jsx as they will need to be translated and therefore must be updatable from the json.

Having it just read the option labels `"Small"`, `"Medium"` etc is perfect. The group title will be read on entry and exit. This is how the mcq currently works.

**Comment by swashbuck** [comment]
@joe-replin I've attempted to fix the merge conflicts with the **master** branch along with a couple other things. Would you mind reviewing this? Hopefully I didn't break anything, but I'm happy to revert it. 😬 

In particular, I wasn't sure which `onChange()` to use: this branch's or master's.

Note: The merge commit [843f181](https://github.com/cgkineo/adapt-visua11y/pull/84/commits/843f1817b4adb86f0f71c7bdb743a4af81286a85) re-added the event functions to the template, but I then removed them in [647fa70](https://github.com/cgkineo/adapt-visua11y/pull/84/commits/647fa704a62d492a6877fd7ad9b0264d9558eb9a).

**Review by oliverfoster — APPROVED** [review]
